use_drag
Hook use_drag for a dragging action.

Does not work because the QDrag.exec() function blocks the main loop.

https://doc.qt.io/qtforpython-6/overviews/qtgui-dnd.html

> “Note that the exec() function does not block the main event loop.”

Not only does it block the main loop, but async Tasks scheduled on the
main loop will fail after a drag with a message like this:

RuntimeError: Cannot enter into task <Task pending name='Task-3' coro=<use_clocktick.<locals>.increment() running at /home/jbrock/work/oth/pyedifice/pyedifice/examples/todomvc.py:31> wait_for=<Future finished result=None> cb=[RenderEngine.use_async.<locals>.<lambda>() at /home/jbrock/work/oth/pyedifice/pyedifice/src/edifice/engine.py:2391]> while another task <Task pending name='Task-4' coro=<use_async_call.<locals>.wrapper() running at /home/jbrock/work/oth/pyedifice/pyedifice/src/edifice/hooks.py:618> cb=[RenderEngine.use_async.<locals>.<lambda>() at /home/jbrock/work/oth/pyedifice/pyedifice/src/edifice/engine.py:2415]> is being executed.